# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Rushi Gajaria
tagline:             'My Thoughts on the World'
description:         'The life of an undergraduate university student in Waterloo. Made by <a href="https://twitter.com/rushigajaria" target="_blank">@rushigajaria</a>.'
url:                 'http://rushi.me'
plugins: [jekyll-paginate]
baseurl:             'http://rushi.me'
paginate: 5
excerpt_separator: "<!--excerpt-->"

# About/contact
author:
  name:              Rushi Gajaria
  url:               https://twitter.com/rushigajaria
  email:             rushigajaria@gmail.com

# Custom vars
version:             1.0.0
